Biblioteka/Models/ErrorViewModel.cs
using System;

namespace Biblioteka.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Biblioteka/Models/Katalog/DjelaDetaljiModel.cs
using PodaciBiblioteke.Modeli;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Biblioteka.Models.Katalog
{
    public class DjelaDetaljiModel
    {
        public int Id{ get; set; }
        public string Naziv { get; set; }
        public string AutorIliReziser { get; set; }
        public string Tip { get; set; }
        public int Godina { get; set; }
        public string ISBN { get; set; }
        public string DeweyIndex { get; set; }
        public string Status { get; set; }
        public decimal Cijena { get; set; }
        public string LokacijaDjela { get; set; }
        public string UrlSlike { get; set; }
        public string ImeRezervatora { get; set; }
        public Iznajmljivanje ZadnjeIznajmljivanje { get; set; }
        public IEnumerable<HistorijaIznajmljivanja> GetHistorijaIznajmljivanja { get; set; }
        public IEnumerable<ZahtjevZaDjelo> TrenutnoZahtjeva { get; set; }



    }
    public class ZahtjevZaDjelo
    {
        public string ImeKlijenta{ get; set; }
        public string DatumZahtjeva { get; set; }

    }
}

Biblioteka/Models/Katalog/DjelaModel.cs
using System.Collections.Generic;

namespace Biblioteka.Models.Katalog
{
    public class DjelaModel
    {
        public IEnumerable<IzlistavanjeDjelaModel> Djela { get; set; }
    }
}

Biblioteka/Models/Katalog/IzlistavanjeDjelaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Biblioteka.Models.Katalog
{
    public class IzlistavanjeDjelaModel
    {
        public int Id { get; set; }
        public string UrlSlike { get; set; }
        public string Naziv{ get; set; }
        public string AutorIliReziser { get; set; }
        public string Tip { get; set; }
        public string DeweyIndex { get; set; }
        public string BrojKopija { get; set; }

    }
}

Biblioteka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Biblioteka.Models;

namespace Biblioteka.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Biblioteka/Controllers/KatalogController.cs
using Biblioteka.Models.Katalog;
using Microsoft.AspNetCore.Mvc;
using PodaciBiblioteke;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Biblioteka.Controllers
{
    public class KatalogController:Controller
    {
        private IBibliotekaDjelo _djela;
        public KatalogController(IBibliotekaDjelo djela)
        {
            _djela = djela;
        }
        public IActionResult Index()
        {
            var djela = _djela.PreuzmiSve();
            var izlistanaDjela = djela.Select(rez => new IzlistavanjeDjelaModel
            {
                Id = rez.ID,
                UrlSlike = rez.UrlSlike,
                AutorIliReziser = _djela.PreuzmiAutoraIliRezisera(rez.ID),
                DeweyIndex = _djela.PreuzmiDeweyIndex(rez.ID),
                Naziv = rez.Naziv,
                Tip = _djela.PreuzmiTip(rez.ID)
            });
            var model = new DjelaModel()
            {
                Djela = izlistanaDjela
            };
            ViewData["djela"] = model;
            return View();

        }
        public IActionResult Detalji(int id)
        {
            var djelo = _djela.PreuzmiPoID(id);
            var model = new DjelaDetaljiModel
            {
                Id = id,
                Naziv = djelo.Naziv,
                Godina = djelo.Godina,
                Cijena = djelo.Cijena,
                Status = djelo.Status.Naziv,
                UrlSlike = djelo.UrlSlike,
                AutorIliReziser = _djela.PreuzmiAutoraIliRezisera(id),
                LokacijaDjela = _djela.LokacijaGdjeSeNalaziDjelo(id).Naziv,
                DeweyIndex=_djela.PreuzmiDeweyIndex(id),
                ISBN=_djela.PreuzmiIsbn(id)
            };

            return View(model);
        }

    }
}

Biblioteka/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<h3>If you want to see library assets, <a href="/Katalog/Index">click  here</a></h3>

Biblioteka/Views/Katalog/Detalji.cshtml
@model Biblioteka.Models.Katalog.DjelaDetaljiModel

<div class="container">
    <div class="page-header clearfix  detailHeading>
        <h2 class="text-muted">Pregled informacija o djelu</h2>
    </div>
</div>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img class="detailImage" src="@Model.UrlSlike" alt="./images/nemacover.png" />
            </div>
        </div>
        <div class="col-md-4">
            <p id="itemTitle">@Model.Naziv</p>
            <p id="itemAuthor">@Model.AutorIliReziser</p>
            <p id="itemStatus">@Model.Status</p>
            <p id="itemType">@Model.Tip</p>
            <p id="itemLocation">@Model.LokacijaDjela</p>

            @if (Model.Status == "Lost")
            {
                <p>Ovo djelo je izgubljeno! Nije ga moguce iznajmiti!</p>
                <p><a class="btn btn-lg btn-danger" role="button" asp-controller="Katalog" asp-action="OznaciKaoPronadjeno" asp-route-id="@Model.Id">Oznaci kao pronadjeno</a></p>

            }

            @if (Model.Status == "Checked out")
            {
                <p id="imeRezervatora">Djelo iznajmio: @Model.ImeRezervatora</p>
                <p><a class="btn btn-lg btn-success" role="button" asp-controller="Katalog" asp-action="VratiDjelo" asp-route-id="@Model.Id">Vrati djelo</a></p>
                <p><a class="btn btn-lg btn-warning" role="button" asp-controller="Katalog" asp-action="RezervisiDjelo" asp-route-id="@Model.Id">Rezervisi djelo</a></p>

            }

            @if (Model.Status == "Available")
            {
                <p><a class="btn btn-lg btn-info" role="button" asp-controller="Katalog" asp-action="IznajmiDjelo" asp-route-id="@Model.Id">Iznajmi</a></p>
            }
        </div>
        <div class="col-md-4 detailInfo>
            <table>
                <tr>
                    <td class="itemLabel">ISBN: </td>
                    <td class="itemValue">@Model.ISBN </td>
                </tr>
                <tr>
                    <td class="itemLabel">Dewy index: </td>
                    <td class="itemValue">@Model.DeweyIndex </td>
                </tr>
                <tr>
                    <td class="itemLabel">Zahtjev iznosi: </td>
                    <td class="itemValue">@Model.Cijena </td>
                </tr>


            </table>



        </div>
    </div>


</div>

Biblioteka/Views/Katalog/Index.cshtml
@using Biblioteka.Models.Katalog
@{
    var Djelo = ViewData["djela"] as DjelaModel;
}

<div id="djela">
    <h3>Katalog biblioteke</h3>
    <div id="tabelaDjela">
        <table class="table table-condensed" id="katalogIndexTabela">
            <thead>
                <tr>
                    <th>Slika</th>
                    <th>Naziv</th>
                    <th>Autor / Reziser</th>
                    <th>Dewey index</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var djelo in Djelo.Djela)
                {
                    <tr>
                        <td>
                            <a asp-controller="Katalog" asp-action="Detalji" asp-route-id="@djelo.Id">
                                <img src="@djelo.UrlSlike" alt="/images/nemacover.png" class="imageCell" />
                            </a>
                        </td>
                        <td>@djelo.Naziv</td>
                        <td>@djelo.AutorIliReziser</td>
                        <td>@djelo.DeweyIndex</td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Biblioteka/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <environment names="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Library</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Library</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Biblioteka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Biblioteka - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>